presets:
  quince_teleop:
    trigger: any
    action:
      - type: quince_teleop
        # Choose from: on_input, continuous
        publish_mode: continuous
        publish_rate: 100
        cmd_vel_topic: quince_vw
        flipper_topic: flipper_control
  flip_front_direction:
    trigger: LSP
    action:
      - type: shared_values
        method: round_robin
        key: front_direction
        values: ['normal', 'inverted']
  change_control_mode:
    trigger: RSP
    action:
      - type: shared_values
        method: round_robin
        key: control_mode
        values: ['normal', 'beginner', 'tank']
  increase_speed_multiplier:
    trigger: C_R
    action:
      - type: shared_values
        method: bidirectional
        direction: increment
        key: speed_multiplier
        values: [0.25, 0.5, 1.0]
  decrease_speed_multiplier:
    trigger: C_L
    action:
      - type: shared_values
        method: bidirectional
        direction: decrement
        decremental: true
        key: speed_multiplier
        values: [0.25, 0.5, 1.0]
  toggle_indep_flippers:
    trigger: Q
    action:
      - type: shared_values
        key: indep_flippers
        values: [false, true]
  flippers_90deg:
    trigger: [L1, L2, R1, R2]
    action:
      - type: flipper_control
        topic: flipper_control
        angle:
          fl: 1.570796
          fr: 1.570796
          rl: 1.570796
          rr: 1.570796
  flippers_0deg:
    trigger: T
    action:
      - type: flipper_control
        topic: flipper_control
        angle:
          fl: 0
          fr: 0
          rl: 0
          rr: 0
  flippers_45deg:
    trigger: T
    action:
      - type: flipper_control
        topic: flipper_control
        angle:
          fl: 0.785398
          fr: 0.785398
          rl: 0.785398
          rr: 0.785398
  flippers_shachihoko:
    # TODO: Check trigger
    trigger: T
    action:
      - type: flipper_control
        topic: flipper_control
        angle:
          fl: 0
          fr: 0
          rl: 0.785398
          rr: 0.785398
