presets:
  quince_teleop:
    trigger: always
    enabled_states: ['chassis']
    action:
      - type: quince_teleop
        cmd_vel_topic: quince_vw
        flipper_topic: flipper_control
        frame_id: quince/chassis/base_link
        flipper:
          step: 0.005
          limits:
            high: 3.1415
            low: -3.1415
        mapping:
          sticks:
            left:
              vertical: LSV
              horizontal: LSH
            right:
              vertical: RSV
              horizontal: RSH
          independent:
            raise: C_U
            lower: C_D
            fl: L1
            fr: R1
            rl: L2
            rr: R2
          synchronized:
            front:
              raise: R1
              lower: R2
            rear:
              raise: L1
              lower: L2
  flip_front_direction:
    trigger: LSP
    enabled_states: ['chassis']
    action:
      - type: shared_values
        method: round_robin
        key: front_direction
        values: ['normal', 'inverted']
  cmd_vel_mode:
    trigger: RSP
    enabled_states: ['chassis']
    action:
      - type: shared_values
        method: round_robin
        key: cmd_vel_mode
        values: ['normal', 'beginner', 'tank']
  increase_scale:
    trigger: C_R
    enabled_states: ['chassis']
    action:
      - type: shared_values
        method: bidirectional
        direction: increment
        key: scale
        initial: 2
        values: [0.25, 0.5, 1.0]
  decrease_scale:
    trigger: C_L
    enabled_states: ['chassis']
    action:
      - type: shared_values
        method: bidirectional
        direction: decrement
        decremental: true
        key: scale
        initial: 2
        values: [0.25, 0.5, 1.0]
  flipper_control_mode:
    trigger: Q
    enabled_states: ['chassis']
    action:
      - type: shared_values
        key: flipper_control_mode
        values: [synchronized, independent]
  flippers_90deg:
    trigger: [[L1, L2, R1, R2]]
    enabled_states: ['chassis']
    action:
      - type: flipper_control
        topic: flipper_control
        angle:
          fl: 1.570796
          fr: 1.570796
          rl: 1.570796
          rr: 1.570796
  flippers_0deg:
    trigger: O
    enabled_states: ['chassis']
    action:
      - type: flipper_control
        topic: flipper_control
        angle:
          fl: 0
          fr: 0
          rl: 0
          rr: 0
  flippers_45deg:
    trigger: T
    enabled_states: ['chassis']
    action:
      - type: flipper_control
        topic: flipper_control
        angle:
          fl: 0.785398
          fr: 0.785398
          rl: 0.785398
          rr: 0.785398
  flippers_shachihoko:
    # TODO: Check trigger
    trigger: X
    enabled_states: ['chassis']
    action:
      - type: flipper_control
        topic: flipper_control
        angle:
          fl: 0
          fr: 0
          rl: 0.785398
          rr: 0.785398
