frame_id: hand
# Don't publish twist if no change is commanded
quiet_on_zero: true
rate: 50
scale:
  translation: 0.05
  rotation: 0.15
  # translation: 0.05
  # rotation: 0.3

presets:
  move_group_name: arm
  open_hand:
    - type: publish_float64
      topic: quince_arm/hand_controller/command
      value: 0.2
  close_hand:
    - type: publish_float64
      topic: quince_arm/hand_controller/command
      value: -1.8
  initial:
    - type: move_group_state
      state_name: initial
  ready_low:
    - type: move_group_state
      state_name: ready_low
  ready_high:
    - type: move_group_state
      state_name: ready_high
  custom_1:
    - type: move_group_state
      state_name: custom_1
  custom_2:
    - type: move_group_state
      state_name: custom_2
  remember_custom_1:
    - type: remember_move_group_state
      state_name: custom_1
  remember_custom_2:
    - type: remember_move_group_state
      state_name: custom_2
  recovery:
    - type: single_point_trajectory
      topic: quince_arm/controller/command
      joints:
        joint4: 0
        joint5: 0
        joint6: -1.5707
      frame_id: arm/base_link
      execution_time: 2.5
    - type: sleep
      duration: 3.0
  rotate_hand_right:
    - type: single_point_trajectory
      topic: quince_arm/controller/command
      joints:
        joint6: 0
      frame_id: arm/base_link
      execution_time: 1.5
  rotate_hand_left:
    - type: single_point_trajectory
      topic: quince_arm/controller/command
      joints:
        joint6: -3.1415
      frame_id: arm/base_link
      execution_time: 1.5
