rate: 50
# Note: Comment out to disable move_group-related presets
move_group_name: arm
timeout:
  press: 0.1
  sequence: 0.2

presets:
presets:
  switch_state_to_chassis:
    trigger: [OP, OP]
    action:
      - type: shared_values
        key: state
        initial: 0
        value: 'chassis'
  switch_state_to_arm:
    trigger: [SH, SH]
    action:
      - type: shared_values
        key: state
        value: 'arm'
  super:
    # Dummy
    trigger: [C_U, C_U, C_D, C_D, C_L, C_R, C_L, C_R, X, O]
    action:
      - type: publish_float64
        topic: foo
        value: 42
