frame_id: hand
# Don't publish twist if no change is commanded
quiet_on_zero: true
rate: 50
hand_topic: /quince_arm/hand_controller/command
scale:
  translation: 0.05
  rotation: 0.3
  # Empirically determined torque to apply
  hand: 5

recovery:
  - type: single_point_trajectory
    topic: quince_arm/controller/command
    joints:
      joint4: 0
      joint5: 0
      joint6: -1.5707
    frame_id: world
    execution_time: 2.5
  - type: sleep
    duration: 3.0
