joy:
  axes:
    # Left Stick Left/Right
    0: LSH
    # Left Stick Up/Down
    1: LSV
    # Right Stick Left/Right
    2: RSH
    # Right Stick Up/Down
    3: RSV
  buttons:
    # Square
    0: Q
    # Triangle
    1: T
    2: X
    3: O
    4:
      name: R1
      as: axis
    5:
      name: L1
      as: axis
    6:
      name: R2
      as: axis
    7:
      name: L2
      as: axis
    8: SH
    9: OP
    10: PS
