mapping:
  # Left Stick Up/Down
  x: a1
  # Left Stick Left/Right
  y: a0
  # Axis 4 (R2) for plus, axis 3 (L2) for minus
  # Active-low with button counterparts
  z: [b7, b6]
  # Axis 2 (Right Stick Left/Right) inverse
  roll: -a2
  # Axis 5 (Right Stick Up/Down)
  pitch: a3
  # Button 4 (R1) for plus (CCW), Button 5 (L1) for minus (CW)
  yaw: [b5, b4]

  presets:
    # Center touch pad
    initial:
      event: triple_press
      index: 10
    # Square
    ready_low:
      event: triple_press
      index: 0
    # Triangle
    ready_high:
      event: triple_press
      index: 1
    # Option
    rotate_hand_left:
      event: triple_press
      index: 9
    # Option
    rotate_hand_right:
      event: long_press
      duration: 1
      index: 9
    # Share button
    recovery:
      event: long_press
      duration: 3
      index: 8
    open_hand:
      event: button_up
      index: 2
    close_hand:
      event: button_up
      index: 3
