mapping:
  # Left Stick Up/Down
  x: a1
  # Left Stick Left/Right
  y: a0
  # Axis 4 (R2) for plus, axis 3 (L2) for minus
  # Active-low with button counterparts
  z: [a5al7, a2al6]
  # Axis 2 (Right Stick Left/Right) inverse
  roll: -a3
  # Axis 5 (Right Stick Up/Down)
  pitch: a4
  # Button 4 (R1) for plus (CCW), Button 5 (L1) for minus (CW)
  yaw: [b4, b5]

  presets:
    # Center touch pad
    initial:
      event: triple_press
      index: 10
    # Square
    ready_low:
      event: triple_press
      index: 3
    # Triangle
    ready_high:
      event: triple_press
      index: 2
    # Option for custom pose
    custom_1:
      event: triple_press
      index: 9
    remember_custom_1:
      event: long_press
      duration: 3
      index: 9
    # Share button
    recovery:
      event: long_press
      duration: 3
      index: 8
    open_hand:
      event: button_up
      index: 0
    close_hand:
      event: button_up
      index: 1
