mapping:
  # Left Stick Up/Down
  x: a1
  # Left Stick Left/Right
  y: a0
  # Axis 4 (R2) for plus, axis 3 (L2) for minus
  # Active-low with button counterparts
  z: [a4al7, a3al6]
  # Axis 2 (Right Stick Left/Right) inverse
  roll: -a2
  # Axis 5 (Right Stick Up/Down)
  pitch: a5
  # Button 4 (R1) for plus (CCW), Button 5 (L1) for minus (CW)
  yaw: [b4, b5]
  # TODO: Support the following format
  # z:
  #   plus:
  #     type: axis
  #     idx: 4
  #     active_low: 7
  #     # active_low: true
  #     # inverted: true
  #   minus:
  #     type: axis
  #     idx: 3
  #     active_low: true

  presets:
    # Center touch pad
    initial:
      event: triple_press
      index: 13
    # Square
    ready_low:
      event: triple_press
      index: 0
    # Triangle
    ready_high:
      event: triple_press
      index: 3
    # Option
    rotate_hand_left:
      event: triple_press
      index: 9
    rotate_hand_right:
      event: long_press
      duration: 1
      index: 9
    custom_1:
      event: triple_press
      index: 12
    remember_custom_1:
      event: long_press
      duration: 3
      index: 12
    # Share button
    recovery:
      event: long_press
      duration: 3
      index: 8
    open_hand:
      event: button_up
      index: 1
    close_hand:
      event: button_up
      index: 2
