mapping:
  # Left Stick Up/Down
  x: a1
  # Left Stick Left/Right
  y: a0
  # Axis 4 (R2) for plus, axis 3 (L2) for minus
  # Active-low with button counterparts
  z: [a4al7, a3al6]
  # Axis 2 (Right Stick Left/Right) inverse
  roll: -a2
  # Axis 5 (Right Stick Up/Down)
  pitch: a5
  # Button 4 (R1) for plus (CCW), Button 5 (L1) for minus (CW)
  yaw: [b4, b5]
  # Hand open (circle) and close (x)
  hand: [b1, b2]
  # TODO: Support the following format
  # z:
  #   plus:
  #     type: axis
  #     idx: 4
  #     active_low: 7
  #     # active_low: true
  #     # inverted: true
  #   minus:
  #     type: axis
  #     idx: 3
  #     active_low: true

presets:
  move_group_name: arm
  # Triple-press to trigger
  mappings:
    # Center touch pad
    initial: 13
    # Square
    ready_low: 0
    # Triangle
    ready_high: 3
    # Option for custom pose
    custom_1: 9
    # PS button for custom pose 2
    custom_2: 12
    # Share button
    recovery: 8
